import type { Breadcrumb } from './breadcrumb.js';
import type { StackFrame } from './stack.js';

/**
 * Event severity level (`fatal` … `debug`).
 * 事件严重级别（`fatal` … `debug`）。
 */
export type EventLevel = 'fatal' | 'error' | 'warning' | 'info' | 'debug';

/**
 * SDK platform identifier (MVP: browser JavaScript only).
 * SDK 平台标识（MVP 仅浏览器 JavaScript）。
 */
export type Platform = 'javascript';

/**
 * SDK metadata embedded in events and envelopes.
 * 嵌入事件与 Envelope 中的 SDK 元数据。
 *
 * @example
 * ```ts
 * // Sample / 示例
 * const sdk: SdkInfo = {
 *   name: 'sentry-guardian.javascript.browser',
 *   version: '0.1.0',
 * };
 * ```
 */
export interface SdkInfo {
  /** SDK package name sent to the server. 上报至服务端的 SDK 包名。 */
  name: string;
  /** SemVer of the SDK build. SDK 构建的语义化版本号。 */
  version: string;
}

/**
 * User context attached to an event (PII may be stripped by the client).
 * 附着在事件上的用户上下文（Client 可能按 PII 策略裁剪）。
 *
 * @example
 * ```ts
 * // Sample / 示例
 * const user: User = { id: '42', email: 'u@example.com', username: 'alice' };
 * ```
 */
export interface User {
  /** Stable user identifier from your app. 应用内稳定的用户 ID。 */
  id?: string;
  /** User email when `sendDefaultPii` allows it. 在允许 PII 时上报的邮箱。 */
  email?: string;
  /** Display username. 展示用用户名。 */
  username?: string;
  /** Client IP when available and allowed. 可用且允许时上报的客户端 IP。 */
  ip_address?: string;
}

/**
 * HTTP request context captured with the event (e.g. page URL).
 * 与事件一并采集的 HTTP 请求上下文（如页面 URL）。
 *
 * @example
 * ```ts
 * // Sample / 示例
 * const request: RequestContext = {
 *   url: 'https://app.example.com/checkout',
 *   headers: { 'User-Agent': 'Mozilla/5.0' },
 * };
 * ```
 */
export interface RequestContext {
  /** Full request or page URL. 完整请求或页面 URL。 */
  url?: string;
  /** Selected HTTP headers (sensitive keys should be scrubbed server-side). 选中的 HTTP 头（敏感键应在服务端脱敏）。 */
  headers?: Record<string, string>;
}

/**
 * How the exception was captured (integration / handler name).
 * 异常被捕获的方式（集成或处理器名称）。
 */
export interface ExceptionMechanism {
  /** Source integration or handler id. 来源集成或处理器标识。 */
  type: string;
  /** Whether the error was handled before capture. 捕获前是否已被业务代码处理。 */
  handled: boolean;
}

/**
 * Stack trace container for one exception value.
 * 单条异常记录附带的堆栈容器。
 */
export interface ExceptionStacktrace {
  /** Ordered stack frames (oldest first after SDK normalization). 有序栈帧（SDK 规范化后最旧帧在前）。 */
  frames: StackFrame[];
}

/**
 * Single exception in the exception chain (innermost or linked `cause`).
 * 异常链中的单条异常（最内层或 `cause` 链中的一环）。
 *
 * @example
 * ```ts
 * // Sample / 示例
 * const ex: ExceptionValue = {
 *   type: 'TypeError',
 *   value: 'Cannot read properties of undefined',
 *   mechanism: { type: 'onerror', handled: false },
 * };
 * ```
 */
export interface ExceptionValue {
  /** Exception constructor name (e.g. `TypeError`). 异常类型名（如 `TypeError`）。 */
  type: string;
  /** Human-readable message or stringified value. 可读消息或字符串化值。 */
  value: string;
  /** Parsed stack frames when available. 可用时的解析后栈帧。 */
  stacktrace?: ExceptionStacktrace;
  /** Capture source and handled flag. 捕获来源与是否已处理标志。 */
  mechanism?: ExceptionMechanism;
}

/**
 * Container for one or more linked exceptions on an event.
 * 事件上一条或多条链接异常的容器。
 */
export interface ExceptionData {
  /** Exceptions from innermost to outermost when `linkedErrors` is enabled. 启用 `linkedErrors` 时从最内到最外的异常列表。 */
  values: ExceptionValue[];
}

/**
 * Error event payload sent by the SDK.
 * SDK 上报的错误事件载荷。
 *
 * @example
 * ```ts
 * // Sample / 示例（Input shape / 输入形态）
 * const event: ErrorEvent = {
 *   event_id: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
 *   timestamp: '2026-06-03T12:00:00.000Z',
 *   platform: 'javascript',
 *   level: 'error',
 *   exception: { values: [{ type: 'Error', value: 'test' }] },
 *   sdk: { name: 'sentry-guardian.javascript.browser', version: '0.1.0' },
 * };
 * ```
 */
export interface ErrorEvent {
  /** Unique event id (UUID v4) generated by the SDK. SDK 生成的唯一事件 ID（UUID v4）。 */
  event_id: string;
  /** ISO 8601 time when the event occurred. 事件发生时间的 ISO 8601 字符串。 */
  timestamp: string;
  /** Runtime platform tag for routing and UI. 用于路由与展示的运行时平台标签。 */
  platform: Platform;
  /** Severity used for filtering and issue level. 用于过滤与 Issue 级别的严重度。 */
  level: EventLevel;
  /** Application release version (e.g. git SHA or semver). 应用发布版本（如 git SHA 或 semver）。 */
  release?: string;
  /** Deployment environment name (e.g. `production`). 部署环境名（如 `production`）。 */
  environment?: string;
  /** Structured exception data when capturing errors. 捕获错误时的结构化异常数据。 */
  exception?: ExceptionData;
  /** Plain-text message when capturing `captureMessage`. 使用 `captureMessage` 时的纯文本消息。 */
  message?: string;
  /** HTTP / page context from integrations. 集成采集的 HTTP / 页面上下文。 */
  request?: RequestContext;
  /** End-user identity and traits. 终端用户身份与属性。 */
  user?: User;
  /** Searchable key-value tags for grouping and filters. 可检索的标签键值对，用于分组与筛选。 */
  tags?: Record<string, string>;
  /** Arbitrary non-indexed diagnostic data. 任意非索引诊断数据。 */
  extra?: Record<string, unknown>;
  /** Chronological user-action trail before the error. 错误前的用户操作时间线。 */
  breadcrumbs?: Breadcrumb[];
  /** Reporting SDK name and version (required). 上报 SDK 名称与版本（必填）。 */
  sdk: SdkInfo;
  /** Optional custom grouping fingerprint; overrides server-side stack hash. 可选自定义聚合指纹，覆盖服务端栈哈希。 */
  fingerprint?: string[];
}
